import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../app_state.dart';

class StoragePage extends StatefulWidget {
  const StoragePage({super.key});

  @override
  State<StoragePage> createState() => _StoragePageState();
}

class _StoragePageState extends State<StoragePage> {
  final FirebaseFirestore firestore = FirebaseFirestore.instance;
  bool isSaving = false;

  final cupBagsController = TextEditingController();
  final paperTowelsController = TextEditingController();
  final spoonBoxesController = TextEditingController();
  final reportController = TextEditingController();

  static const int cupBagsLow = 2;
  static const int paperTowelsLow = 2;
  static const int spoonBoxesLow = 1;

  String? _loadedLocation;

  bool _isLow(TextEditingController controller, int threshold) {
    final value = int.tryParse(controller.text);
    if (value == null) return false;
    return value <= threshold;
  }

  Future<void> _loadStorage(String location) async {
    try {
      final doc = await firestore.collection('storage').doc(location).get();
      if (doc.exists) {
        final data = doc.data() as Map<String, dynamic>;
        setState(() {
          cupBagsController.text = data['cupBags']?.toString() ?? '';
          paperTowelsController.text = data['paperTowels']?.toString() ?? '';
          spoonBoxesController.text = data['spoonBoxes']?.toString() ?? '';
        });
      }
    } catch (e) {
      print("Error loading storage: $e");
    }
  }

  // NEW: Auto-create reports for low stock items
  Future<void> _checkAndReportLowStock(String location) async {
    List<String> lowItems = [];

    print("Checking low stock for $location");
    print("Cup Bags: ${cupBagsController.text}, threshold: $cupBagsLow");
    print("Paper Towels: ${paperTowelsController.text}, threshold: $paperTowelsLow");
    print("Spoon Boxes: ${spoonBoxesController.text}, threshold: $spoonBoxesLow");

    if (_isLow(cupBagsController, cupBagsLow)) {
      lowItems.add("Cup Bags (${cupBagsController.text} remaining)");
    }
    if (_isLow(paperTowelsController, paperTowelsLow)) {
      lowItems.add("Paper Towels (${paperTowelsController.text} remaining)");
    }
    if (_isLow(spoonBoxesController, spoonBoxesLow)) {
      lowItems.add("Spoon Boxes (${spoonBoxesController.text} remaining)");
    }

    print("Low items found: $lowItems");

    if (lowItems.isEmpty) {
      print("No low items, skipping report");
      return;
    }

    try {
      // Check if there's already an unresolved report for this location about low stock
      final existingReports = await firestore
          .collection('reports')
          .where('location', isEqualTo: location)
          .where('resolved', isEqualTo: false)
          .where('isAutoGenerated', isEqualTo: true)
          .get();

      print("Found ${existingReports.docs.length} existing auto-reports");

      // If there's already an unresolved auto-report, update it instead of creating new
      if (existingReports.docs.isNotEmpty) {
        print("Updating existing report");
        await firestore.collection('reports').doc(existingReports.docs.first.id).update({
          'message': 'Low stock alert:\n• ${lowItems.join('\n• ')}',
          'timestamp': FieldValue.serverTimestamp(),
        });
        print("Report updated successfully");
      } else {
        print("Creating new auto-report");
        // Create new auto-generated report
        await firestore.collection('reports').add({
          'location': location,
          'message': 'Low stock alert:\n• ${lowItems.join('\n• ')}',
          'timestamp': FieldValue.serverTimestamp(),
          'resolved': false,
          'isAutoGenerated': true, // Mark as auto-generated
        });
        print("Report created successfully");
      }
    } catch (e) {
      print("ERROR creating/updating auto-report: $e");
      // Don't show error to user since this is background
    }
  }

  Future<void> _saveStorage(String location) async {
    setState(() => isSaving = true);

    try {
      await firestore.collection('storage').doc(location).set({
        'cupBags': int.tryParse(cupBagsController.text),
        'paperTowels': int.tryParse(paperTowelsController.text),
        'spoonBoxes': int.tryParse(spoonBoxesController.text),
        'lastUpdated': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      // NEW: Auto-report low stock
      await _checkAndReportLowStock(location);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Storage updated!"), backgroundColor: Colors.green),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red),
      );
    }

    setState(() => isSaving = false);
  }

  Future<void> _sendReport(String location) async {
    if (reportController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Please describe the issue first")),
      );
      return;
    }

    try {
      await firestore.collection('reports').add({
        'location': location,
        'message': reportController.text.trim(),
        'timestamp': FieldValue.serverTimestamp(),
        'resolved': false,
        'isAutoGenerated': false, // Manual report from worker
      });

      reportController.clear();

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text("Report submitted! Managers will be notified soon."),
          backgroundColor: Colors.green,
        ),
      );
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Error: $e"), backgroundColor: Colors.red),
      );
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final location = Provider.of<AppState>(context, listen: false).currentLocation;
    if (location != null && location != _loadedLocation) {
      _loadedLocation = location;
      _loadStorage(location);
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentLocation = Provider.of<AppState>(context).currentLocation;

    if (currentLocation == null) {
      return Scaffold(
        appBar: AppBar(
          title: Text("Storage"),
          backgroundColor: Colors.green,
        ),
        body: Center(
          child: Text(
            "You must be working at a location to view storage",
            style: TextStyle(fontSize: 16),
            textAlign: TextAlign.center,
          ),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text("Storage – $currentLocation"),
        backgroundColor: Colors.green,
      ),
      body: ListView(
        padding: EdgeInsets.all(16),
        children: [
          _sectionHeader("Inventory", Icons.inventory_2),

          SizedBox(height: 12),

          _storageField(
            label: "Cup Bags",
            controller: cupBagsController,
            isLow: _isLow(cupBagsController, cupBagsLow),
            lowMessage: "Low on cup bags!",
          ),

          _storageField(
            label: "Paper Towels",
            controller: paperTowelsController,
            isLow: _isLow(paperTowelsController, paperTowelsLow),
            lowMessage: "Low on paper towels!",
          ),

          _storageField(
            label: "Spoon Boxes",
            controller: spoonBoxesController,
            isLow: _isLow(spoonBoxesController, spoonBoxesLow),
            lowMessage: "Low on spoon boxes!",
          ),

          SizedBox(height: 20),

          ElevatedButton(
            onPressed: isSaving ? null : () => _saveStorage(currentLocation),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.green,
              minimumSize: Size(double.infinity, 50),
            ),
            child: isSaving
                ? CircularProgressIndicator(color: Colors.white)
                : Text(
              "Save Storage",
              style: TextStyle(fontSize: 18, color: Colors.white),
            ),
          ),

          SizedBox(height: 30),

          _sectionHeader("Report an Issue", Icons.flag),

          SizedBox(height: 12),

          Text(
            "Report low stock or any other issue to managers.",
            style: TextStyle(color: Colors.grey[600], fontSize: 14),
          ),

          SizedBox(height: 12),

          TextField(
            controller: reportController,
            maxLines: 3,
            decoration: InputDecoration(
              hintText: "e.g. Need more napkins...",
              border: OutlineInputBorder(),
              filled: true,
              fillColor: Colors.grey[50],
            ),
          ),

          SizedBox(height: 12),

          ElevatedButton.icon(
            onPressed: () => _sendReport(currentLocation),
            icon: Icon(Icons.send),
            label: Text("Send Report to Managers"),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.orange,
              foregroundColor: Colors.white,
              minimumSize: Size(double.infinity, 50),
            ),
          ),
        ],
      ),
    );
  }

  Widget _sectionHeader(String title, IconData icon) {
    return Row(
      children: [
        Icon(icon, color: Colors.green),
        SizedBox(width: 8),
        Text(
          title,
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Colors.green[800],
          ),
        ),
      ],
    );
  }

  Widget _storageField({
    required String label,
    required TextEditingController controller,
    required bool isLow,
    required String lowMessage,
  }) {
    return Padding(
      padding: EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          TextField(
            controller: controller,
            keyboardType: TextInputType.number,
            onChanged: (v) => setState(() {}),
            decoration: InputDecoration(
              labelText: label,
              border: OutlineInputBorder(
                borderSide: BorderSide(
                  color: isLow ? Colors.red : Colors.green,
                  width: 2,
                ),
              ),
              enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(
                  color: isLow ? Colors.red : Colors.grey,
                  width: isLow ? 2 : 1,
                ),
              ),
              filled: true,
              fillColor: isLow ? Colors.red[50] : Colors.white,
              suffixIcon: isLow
                  ? Icon(Icons.warning_amber, color: Colors.red)
                  : Icon(Icons.check_circle_outline, color: Colors.green),
            ),
          ),
          if (isLow)
            Padding(
              padding: EdgeInsets.only(top: 4, left: 4),
              child: Text(
                "⚠️ $lowMessage",
                style: TextStyle(
                  color: Colors.red,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
        ],
      ),
    );
  }
}
